spring:
  application:
    name: AUTH
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3307/netflix
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081


