spring:
  application:
    name: AUTH

  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: ab12+-34

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
