spring:
  application:
    name: AUTH
  datasource:
    url: jdbc:mysql://localhost:3307/netflix
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

user:
  service:
    url: http://user:8082/api/users/

server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka
