services:
  
#  eureka:
#    image: adityazaware/eureka_server:0.0.1
#    container_name: eureka
#    ports:
#      - "8761:8761"
#    networks:
#      - netflix
#
#  config:
#    image: adityazaware/config_server:0.0.1
#    container_name: config
#    ports:
#      - "8888:8888"
#    networks:
#      - netflix
#
#  gateway:
#    image: adityazaware/apigateway:0.0.1
#    container_name: gateway
#    ports:
#      - "9090:9090"
#    depends_on:
#      - config
#    networks:
#      - netflix
#
#  auth:
#    image: adityazaware/auth_service:0.0.1
#    container_name: auth
#    ports:
#      - "8081:8081"
#    depends_on:
#      - config
#      - mysql
#    networks:
#      - netflix
#
#  user:
#    image: adityazaware/user_service:0.0.1
#    container_name: user
#    ports:
#      - "8082:8082"
#    depends_on:
#      - config
#      - mysql
#    networks:
#      - netflix
#
#  subscription:
#    image: adityazaware/subscription_service:0.0.1
#    container_name: subscription
#    ports:
#      - "8083:8083"
#    depends_on:
#      - eureka
#      - mysql
#    networks:
#      - netflix
#
#  stream:
#    image: adityazaware/stream_service:0.0.1
#    container_name: stream
#    ports:
#      - "8084:8084"
#    depends_on:
#      - config
#      - mysql
#    networks:
#      - netflix
#
#  history:
#    image: adityazaware/history_service:0.0.1
#    container_name: history
#    ports:
#      - "8085:8085"
#    depends_on:
#      - config
#      - mysql
#    networks:
#      - netflix
  
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netflix
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - netflix

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - netflix

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - 22181:2181
    networks:
      - netflix
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - netflix


networks:
  netflix:
    driver: bridge

volumes:
  mysql:
