spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/user/**
              - Path=/api/auth/**

          - id: STREAM-SERVICE
            uri: lb://STREAM-SERVICE
            predicates:
              - Path=/api/stream/**
            filters:
              - AuthFilter

          - id: HISTORY-SERVICE
            uri: lb://HISTORY-SERVICE
            predicates:
              - Path=/api/history/**
            filters:
              - AuthFilter



eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:8761/eureka

server:
  port: 9090