apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done']
      - name: wait-for-eureka
        image: busybox
        command: ['sh', '-c', 'until nc -z eurekaserver 8761; do echo waiting for eureka; sleep 2; done']
      - name: wait-for-apis
        image: busybox
        command: ['sh', '-c', 'until nc -z apis 9090; do echo waiting for apis; sleep 2; done']
        
      containers:
        - name: authservice
          image: adityazaware/authservice:0.0.1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/netflix
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: pass
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP