
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9090
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: SUBSCRIPTION
          uri: http://subscription:8083
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter

        - id: AUTH
          uri: http://auth:8081
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: USER
          uri: http://user:8082
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: STREAM-SERVICE
          uri: http://stream:8084
          predicates:
            - Path=/api/video/**
          filters:
            - AuthenticationFilter


