spring:
  application:
    name: SUBSCRIPTION-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/netflix
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

razorpay:
  api:
    key: rzp_test_COl2jK69K1rzy2
    secret: 2yRakSKsYqXIxR2DB77e00Zs


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:8761/eureka