spring:

  application:
    name: HISTORY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3307/netflix
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: history-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8085


video:
  service:
    url: http://localhost:8084/api/content/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

