spring:
  application:
    name: STREAM-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3307/netflix
    username: user
    password: pass

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

user:
  service:
    url: http://userservice:8082/api/users/

files:
  video: videos/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/

server:
  port: 8084
