spring:
  application:
    name: STREAM-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3306/netflix
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB


files:
  video: videos/

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:8761/eureka

server:
  port: 8087
